spring.application.name=goOUT

spring.mongodb.uri=mongodb://localhost:27017/triplink_db

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=goout.0x09.project@gmail.com
spring.mail.password=sgez xden mdvi qsuk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
