spring.application.name=goOUT

# 🌟 THE FIX: Added "data" to the property name and "goout_db" before the question mark!
spring.mongodb.uri=mongodb+srv://gooutadmin:goout123@cluster0.tzj4qm9.mongodb.net/triplink_db?appName=Cluster0

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=goout.0x09.project@gmail.com
spring.mail.password=sgez xden mdvi qsuk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true